name: C++ Build Check

on:
  push:
    branches: ["main", "ci-build-cache"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Cache External Libraries
        uses: actions/cache@v3
        with:
          path: |
            ${{github.workspace}}/external/SDL
            ${{github.workspace}}/external/wxWidgets
            ${{github.workspace}}/build/CMakeCache.txt
            ${{github.workspace}}/build/CMakeFiles
            ${{github.workspace}}/build/Makefile
            ${{github.workspace}}/build/compile_commands.json
          key:
            ${{ runner.os }}-build-${{ env.BUILD_TYPE }}-${{ hashFiles('CMakeLists.txt',
            'external/SDL/**', 'external/wxWidgets/**') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.BUILD_TYPE }}-

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libgtk-3-dev

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSDL_UNIX_CONSOLE_BUILD=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
