name: C++ Build Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: |
            ${{github.workspace}}/build
            !${{github.workspace}}/build/CMakeCache.txt
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.cpp', '**/*.h', 'CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-
