name: Build and Test

on:
  push:
    branches:
      - main
      - new_gui
  pull_request:
    branches:
      - main
      - new_gui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true  # <== Fixes missing SDL & wxWidgets
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            cmake g++ \
            libgtk-3-dev \
            libwxgtk3.2-dev \
            libsdl2-dev \
            libasound2-dev \
            libjack-dev \
            libpipewire-0.3-dev \
            libpulse-dev \
            libdrm-dev \
            libgbm-dev \
            libwayland-dev \
            libxkbcommon-dev \
            libunwind-dev 

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DSDL_UNIX_CONSOLE_BUILD=ON

      - name: Build Project
        run: cmake --build build -- -j$(nproc)

      - name: Run Tests (if applicable)
        run: |
          cd build
          ctest --output-on-failure
