# https://claude.site/artifacts/cb4f8ae5-253c-44f2-bc08-5d34cd0ef6e6
name: Clang Tidy
on:
  push:
    branches: ["main", "clang-tidy-severity-fix"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  tidiness-check:
    name: Static Analysis Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install clang-tidy and dependencies
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
          sudo apt-get install -y clang-tidy-19
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-19 100

      - name: Verify .clang-tidy exists
        run: |
          if [ ! -f .clang-tidy ]; then
            echo "Error: .clang-tidy file not found in repository root"
            exit 1
          fi

      - name: Cache SDL Build
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build
            ${{ github.workspace }}/external/SDL
          key: ${{ runner.os }}-sdl-${{ hashFiles('external/SDL/**') }}
          restore-keys: |
            ${{ runner.os }}-sdl-

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSDL_UNIX_CONSOLE_BUILD=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Generate compilation database
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          mv build/compile_commands.json .

      - name: Run clang-tidy
        run: |
          TIDY_ISSUES=0
          for file in $(find ./src -type f \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \)); do
            echo "Analyzing $file..."
            if ! clang-tidy "$file" -p . > tidy_output.txt 2>&1; then
              TIDY_ISSUES=1
              echo "::error::Clang-tidy issues found in $file"
              cat tidy_output.txt
            fi
          done
          if [ $TIDY_ISSUES -ne 0 ]; then
            echo "Static analysis check failed. Please fix the issues reported by clang-tidy."
            exit 1
          else
            echo "All files passed static analysis."
          fi
