# https://claude.site/artifacts/cb4f8ae5-253c-44f2-bc08-5d34cd0ef6e6
name: Clang Tidy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  tidiness-check:
    name: Static Analysis Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install clang-tidy and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy

      - name: Verify .clang-tidy exists
        run: |
          if [ ! -f .clang-tidy ]; then
            echo "Error: .clang-tidy file not found in repository root"
            exit 1
          fi

      - name: Cache External Builds
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build
            ${{ github.workspace }}/external/SDL
            ${{ github.workspace }}/external/wxWidgets
          key:
            ${{ runner.os }}-external-${{ hashFiles('external/SDL/**', 'external/wxWidgets/**') }}
          restore-keys: |
            ${{ runner.os }}-external-

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libgtk-3-dev

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSDL_UNIX_CONSOLE_BUILD=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Generate compilation database
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          mv build/compile_commands.json .

      - name: Run clang-tidy
        run: |
          clang-tidy src/*.cpp src/*.h -p compile_commands.json -warnings-as-errors=*
