name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Headless

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Cache External Builds
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build
            ${{ github.workspace }}/external/SDL
            ${{ github.workspace }}/external/wxWidgets
          key:
            ${{ runner.os }}-external-${{ hashFiles('external/SDL/**', 'external/wxWidgets/**') }}
          restore-keys: |
            ${{ runner.os }}-external-

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libgtk-3-dev

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSDL_UNIX_CONSOLE_BUILD=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Run Hello World 1
        run: |
          ./starter-code/tests/run_test.sh \
          ./starter-code/tests/hello_world1 \
          ./build/emulator \
          ./starter-code/hws/hello_world1.slug
        working-directory: ${{ github.workspace }}

      - name: Run Hello World 2
        run: |
          ./starter-code/tests/run_test.sh \
          ./starter-code/tests/hello_world2 \
          ./build/emulator \
          ./starter-code/hws/hello_world2.slug
        working-directory: ${{ github.workspace }}

      - name: Run Hello World 3
        run: |
          ./starter-code/tests/run_test.sh \
          ./starter-code/tests/hello_world3 \
          ./build/emulator \
          ./starter-code/hws/hello_world3.slug
        working-directory: ${{ github.workspace }}
